### ISSUE TITLE
Post catastrophic errors to Conbench

### ISSUE THREAD

**Issue by alistaire47** [voltrondata-labs/benchmarks#145]
Right now, we're catching catastrophic benchmark failures, but not posting them to Conbench: https://github.com/voltrondata-labs/benchmarks/pull/143#discussion_r1237842468

After https://github.com/voltrondata-labs/arrow-benchmarks-ci/issues/146 is resolved (likely by https://github.com/eddelbuettel/digest/issues/189 resulting in a patch), we should turn on posting here: https://github.com/voltrondata-labs/benchmarks/blob/main/benchmarks/_benchmark.py#L252-L282 (Doing so before will result in a lot of messages on PRs that there are errored benchmarks, but the cause of the error is out of the committer's scope.)

**Comment by alistaire47** [comment]
After further investigation, the issues are happening on arrow build: https://github.com/apache/arrow/blob/4198aacf8ab369d2ec3b7cb539f96c189f4a86f3/ci/scripts/r_deps.sh#L46 This change won't catch and post it, but it's likely still valuable. And there's no need to wait.

**Comment by jgehrcke** [comment]
> Post catastrophic errors to Conbench

There's value in that thinking; and this seems to be in line with some things that were decided in the past. I do not want to dismiss that! 

Yet, should relate this to https://github.com/conbench/conbench/issues/1251 and we should not be afraid of making strict, definite decisions for the time being.

All of Conbench as we use it today has a bit of an unhappy and resource-wasting error handling story with blurry separation of concerns.

I see this topic as a laaaarge opportunity to save eng/people/time resources and to overall make users a little more happy (via good expectation management) and therefore I really advise for taking https://github.com/conbench/conbench/issues/1251 a little further.

Decisions should be derived logically from clear goal/problem statements.

We should try to narrow down the goal(s) of "posting catastrophic errors to Conbench"; that makes it easier to see
- if these goals are potentially in conflict with other goals
- potentially in conflict with fundamental technical constraints
- if these goals can potentially be reached easier via other means

https://github.com/conbench/conbench/issues/1251 has a lot of text; but the core hypothesis is

> The stability of those runs should not be assessed by consuming data from Conbench, but from the CI runner's environment alone.

**Comment by austin3dickey** [comment]
Thanks for the thoughts, @jgehrcke. Ultimately the creation of this ticket was driven by the following events:
- Arrow R benchmarks suddenly started to fail upon attempting to create a benchmark-running environment (before we got to running benchmarks)
- No action was taken for a while
- I finally logged into Buildkite for something unrelated, and noticed something was up

So the goal of this ticket is to enable the "right" people to be notified when benchmark setup fails in the future.

Who are the right people? It's still a tricky question today with the blurry ownership of this repo. I'd lean toward over-notifying when catastrophic failures like this occur, so that the right person will see it. So I'd like you, myself, and @alistaire47 to be notified (as the de facto owners of arrow-benchmarks-ci), as well as the project code owners (who are de facto owners of benchmark code too).

One incredibly easy way to achieve this goal is Ed's 2-line PR: https://github.com/voltrondata-labs/benchmarks/pull/146. This will notify project code owners via PR comments when benchmarks fail in this case, and will notify us via Slack as well. I'm heavily in favor of doing this in the short term because its value-to-effort ratio is high. It's like what Jon said in https://github.com/conbench/conbench/issues/1251#issuecomment-1546060226:

>Having conbench be a repository of this error information isn't the only way to go about this, but is one that has helped other instances close the circle on failure -> fix much quicker

But I also agree that https://github.com/conbench/conbench/issues/1251 is an important goal that will reduce complexity and our burden of maintenance in the future. I think we absolutely should work toward that state and deprecate this approach once we get there.

**Comment by jgehrcke** [comment]
Let's do https://github.com/voltrondata-labs/benchmarks/pull/146. I don't mind too much :).

I want to say that we had/have an opportunity here that if we don't use it it tells me that we're maybe not honest with ourselves; if we don't turn "right" today, why should we do it tomorrow?

Not claiming absolute truth, but to make this a little more specific:

If I were to spend 30 minutes today to work on a solution then I'd rather invest that time into a notification approach that does not involve Conbench, but only buildkite notification primitives (Slack, email).

> https://github.com/conbench/conbench/issues/1251 is an important goal that will reduce complexity and our burden of maintenance in the future. I think we absolutely should work toward that state and deprecate this approach once we get there.

:+1: but maybe I triggered a bit of a misunderstanding; I think this is a little more actionable than "let's maybe do this soon, and it's a lot of work".

Let me elaborate? :) I don't expect a reply here and don't want to disturb anyone's day. Just trying myself to lay out some arguments that I believe I have in my mind (but we all gain clarity by trying to write).

---

> driven by the following events:

:+1: 

> So the goal of this ticket is to enable the "right" people to be notified when benchmark setup fails in the future.

Good problem statement! :)

I try to make the problem statement a little more general, but also a tiny more specific: when the CI job fails then a set of people must be alerted via email, with reliability (in addition: via a Slack notification ... and potentially via other channels).

> when the CI job fails

(just to be explicit: this of course includes the special case of benchmark setup error).

As a solution, I recommend and propose a notification / alerting information flow  _without traversing Conbench components_, but to use the CI runner's notification system. Relying mostly or exclusively on infra _not_ built and operated by us. In this case this is probably all about https://buildkite.com/docs/pipelines/notifications.

----

I think I'd love to dive a little further into the impact/effort ratio! 

> value-to-effort ratio is high

Agree, kind of :) But maybe there's an alternative path with a (_much_?) better value-to-effort ratio? :) :bulb: 

This is a good moment to dive a little deeper into discussion. That discussion takes longer than iterating on the solution. But I think it's worth it.

Let me try to compare, slightly ignorantly:

1) going through Conbench components: little work, less errors covered, less reliable information flow
2) using only buildkite/slack/email: little work, more errors covered, more reliable information flow

When comparing the two, I think that the more important bit here is that doing (2) has the additional "hidden" value of _not_ digging deeper into (1): with approach (1) we rely on a hole that we have dug before :hammer:, and we dig ourselves into it a tiny little further.

My recommendation would be to use every opportunity to move up, instead of further down in that hole. To work against the trend, so to say. Working against the trend has a lot of abstract value; and that can shift the trueish value/effort ratio quite a bit.

I never replied in detail to https://github.com/conbench/conbench/issues/1251#issuecomment-1546060226 but the following statement is a (IMO wrong) belief, not an argument:

>  is one that has helped other instances close the circle on failure -> fix much quicker

It says "quicker"; but I have not seen a comparison, and this contradicts my experience. When CI jobs are generally green and properly monitored with (reliable) notification-upon-red then to me this is obviously the best way towards reliable, fast response. 

https://github.com/conbench/conbench/issues/1251#issuecomment-1546060226 also mentions https://github.com/apache/arrow/issues/35383 and the difficulty of reading build logs. That is true: understanding a problem from logs is often time-consuming. But it's also true it's _much_ harder to always automatically pass the relevant error information to an external system. I am saying: for the trivial errors it's easy to understand them based on the build log as well as based on the err fragments in Conbench. For the non-trivial errors it's possible to understand them based on the full build log but _not_ possible to see the full picture based on the err fragments in Conbench. Also, the impulse on `arrow/issues/35383 ` with "Can we improve log output?" is in my experience exactly the right direction/incentive.

My current point of view: error propagation through Conbench is a nice/cute idea! It can be sugar, an optimization! But as the sole solution, it is conceptually unable to live up to expectations. This strongly relates to https://github.com/conbench/conbench/issues/1227.

Let's see where this all goes :)

**Comment by austin3dickey** [comment]
Love the breakdown here! And I admit, I had completely forgotten about the https://buildkite.com/docs/pipelines/notifications option. That's also a very quick change that probably covers more use cases. I will add myself to email notifications upon pipeline failures after https://github.com/voltrondata-labs/arrow-benchmarks-ci/issues/146 is resolved.
